[package]
name = "z-biz-tool-box"
version = "0.1.0"
description = "插件化工具箱"
edition = "2021"

[lib]
name = "z_biz_tool_box_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = "0.2"
reqwest = { version = "0.12", features = ["json", "blocking"] }
chrono = "0.4"
